### ISSUE TITLE
Hover on to animate screenshots

### ISSUE THREAD

**Issue by booyaa** [booyaa/rustlangserver.github.io#2]
- better example w/o jquery: http://jsfiddle.net/booyaa/41tauehx/
- [extracting the first frame from a gif](https://stackoverflow.com/questions/21260529/how-can-i-extract-the-first-frame-of-an-animated-gif-using-imagemagicks-convert)
----
- example: http://jsfiddle.net/EXNZr/1/

**Comment by liamdawson** [comment]
Maybe an alternative (thought not seen before with Rust docs) is the tabs-beside-a-picture pattern?

(Like this, roughly) - lets people explore if interested, without needing too much scrolling to move on.
(Not sure how people make this work with mobile, exactly)

![tabs2](https://user-images.githubusercontent.com/760143/29741184-e408069e-8aaa-11e7-8431-0ce6b105c6bc.jpg)

**Comment by booyaa** [comment]
resolved by 53339437a9084b23fbf69db52e59d619a7acdbe7
